# Generated by Django 6.0.5 on 2026-05-19 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'annonce")),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('contenu', models.TextField(verbose_name="Contenu de l'annonce ou de l'article")),
                ('image', models.ImageField(blank=True, null=True, upload_to='annonces/', verbose_name="Image d'illustration")),
                ('est_epinglee', models.BooleanField(default=False, verbose_name='Épingler en haut de page (Important)')),
                ('est_active', models.BooleanField(default=True, verbose_name="Publier l'annonce")),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Annonce / Actualité',
                'verbose_name_plural': 'Annonces / Actualités',
                'ordering': ['-est_epinglee', '-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(help_text="Sert pour l'URL (ex: informatique-web)", max_length=100, unique=True)),
                ('icone', models.CharField(blank=True, help_text="Nom de l'icône (ex: fas fa-laptop)", max_length=50)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'entreprise / partenaire")),
                ('logo', models.ImageField(upload_to='partenaires/', verbose_name='Logo du partenaire')),
                ('site_web', models.URLField(blank=True, null=True, verbose_name='Lien vers leur site web (Optionnel)')),
                ('ordre_affichage', models.IntegerField(default=0, verbose_name="Ordre d'affichage (ex: 1, 2, 3...)")),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la formation')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description_courte', models.TextField(max_length=300, verbose_name='Description courte (pour les cartes)')),
                ('programme_detaille', models.TextField(verbose_name='Programme détaillé')),
                ('duree', models.CharField(max_length=50, verbose_name='Durée (ex: 3 mois / 120 heures)')),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix (FCFA / €)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='formations/', verbose_name="Image d'illustration")),
                ('est_active', models.BooleanField(default=True, verbose_name='Afficher sur le site')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='mon_app.categorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='DemandeContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Numéro de Téléphone')),
                ('message', models.TextField(verbose_name='Message / Questions')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False, verbose_name='Traité / Lu')),
                ('formation_interet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mon_app.formation', verbose_name='Formation concernée')),
            ],
            options={
                'verbose_name': 'Demande de contact',
                'verbose_name_plural': 'Demandes de contact',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
