# Generated by Django 6.0.5 on 2026-05-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='categorie',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
