# Generated by Django 6.0.5 on 2026-05-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0002_remove_formation_categorie_delete_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'evenement")),
                ('contenu', models.TextField(verbose_name="Contenu de l'annonce ou de l'article")),
                ('image', models.ImageField(blank=True, null=True, upload_to='annonces/', verbose_name="Image d'illustration")),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'ordering': ['titre'],
            },
        ),
    ]
