# Generated by Django 6.0.5 on 2026-05-23 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0003_albumphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandecontact',
            name='formation_interet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='mon_app.formation', verbose_name='Formation concernée'),
        ),
    ]
