# Generated by Django 6.0.5 on 2026-05-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0004_alter_demandecontact_formation_interet'),
    ]

    operations = [
        migrations.CreateModel(
            name='utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'utilisateur")),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='formation',
            name='categorie',
            field=models.CharField(choices=[('Paramedical', 'Paramedical'), ('Industrielle', 'Industrielle')], default='Paramedical', max_length=50),
        ),
    ]
