# Generated by Django 6.0.5 on 2026-06-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0005_utilisateur_formation_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250, verbose_name="Titre de l'actualité")),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='actualites/', verbose_name="Image d'illustration")),
                ('contenu', models.TextField(verbose_name="Contenu de l'article")),
                ('statut', models.CharField(choices=[('Brouillon', 'Brouillon'), ('Publie', 'Publié')], default='Publie', max_length=20)),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date_publication'],
            },
        ),
    ]
