# Generated by Django 5.2.12 on 2026-06-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0007_remove_formation_prix_alter_actualite_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='programme_detaille',
            field=models.TextField(verbose_name='Niveau requis et débouchés'),
        ),
    ]
