# Generated by Django 5.2.12 on 2026-06-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0008_alter_formation_programme_detaille'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='programme_detaille',
        ),
        migrations.AddField(
            model_name='formation',
            name='debouches',
            field=models.TextField(blank=True, null=True, verbose_name='Débouchés professionnels'),
        ),
        migrations.AddField(
            model_name='formation',
            name='niveau_requis',
            field=models.TextField(blank=True, null=True, verbose_name='Niveau requis'),
        ),
    ]
