# Generated by Django 5.2.12 on 2026-06-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0009_remove_formation_programme_detaille_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albumphoto',
            options={'verbose_name': "Photo d'album", 'verbose_name_plural': 'Album Photos'},
        ),
        migrations.RemoveField(
            model_name='albumphoto',
            name='contenu',
        ),
        migrations.RemoveField(
            model_name='albumphoto',
            name='titre',
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='albums/', verbose_name="Image de l'album"),
        ),
        migrations.AlterField(
            model_name='formation',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
